services:
  - type: web
    name: zara-monitor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python monitor.py
    envVars:
      - key: PORT
        value: 10000
